<a href="https://colab.research.google.com/github/arkapravo-dey/Numpy_Basics/blob/main/Starting_with_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Numpy is a Python library used for performing linear algebra operations in Python

**First lets install numpy in the local environment

In [ ]:
!pip install numpy

**Importing Numpy library as np for more convenience while
writing the code

In [ ]:
import numpy as np

** When we use numpy arrays for machine learning or data science, we deal with numpy arrays. Numpy arrays are broadly of two types :-


*   Matrices - Matrices are usually two dimensional
*   Vectors - Vectors are strictly one dimensional. So vectors are a subset of matrices



**Creating a list and the converting it into an 1Dimensional array

In [ ]:
list1 = [1,2,3,4]
array1 = np.array(list1)
print(array1)

[1 2 3 4]


**Creating a list of list and converting it into a multi-dimensional array

In [ ]:
list2 = [[1,2,3],[4,5,6],[7,8,9]]
np.array(list2)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**Numpy arrays using built-in methods

**(start,stop,step)

In [ ]:
np.arange(0,10,1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr1 = np.arange(0,15,2) #arr1 = [0,2,4,6,8,10,12,14]
arr1.size

8

**Array of zeroes

In [ ]:
arr = np.zeros(5)
print(arr)
arr.dtype

[0. 0. 0. 0. 0.]


dtype('float64')

In [ ]:
a = np.zeros((3,2)) #(rows,columns)
print(a)
a.dtype

[[0. 0.]
 [0. 0.]
 [0. 0.]]


dtype('float64')

**Creating an array of ones(similar to what we have done for zeroes)

In [ ]:
print(np.ones((5,3)).dtype)
print(np.ones((5,3)))

float64
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


**Creating an identity matrix

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**Creating a random array of dimension(a,b)

In [ ]:
np.random.rand(4,2)

array([[0.78958972, 0.45653691],
       [0.86109375, 0.10862068],
       [0.96861885, 0.66786927],
       [0.66082138, 0.67903059]])

**Some built-in array operations

In [ ]:
arr1 = np.arange(10,100,5)
arr1

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [ ]:
print(arr1.shape)
print(arr1.size)

(18,)
18


In [ ]:
arr = arr1.reshape(2,9)
print(arr.shape)
print(arr.size)

(2, 9)
18


**Finding the maximum and minimum elements

In [ ]:
print(arr1.max())
print(arr1.min())

95
10


In [ ]:
print(arr1.shape)
print(arr.shape)

(18,)
(2, 9)


In [ ]:
print(arr1)

[10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


**1D arrays

In [ ]:
arr1[17] #arrays follow 0 based indexing

95

In [ ]:
arr1[1:6] #prints elements in the array with index 2,3,4

array([15, 20, 25, 30, 35])

In [ ]:
arr1_copy=arr1.copy()
arr1_copy[12:16]=60 #replace 60 in the index positions 12,13,14 and 15
arr1_copy

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 60, 60, 60, 60, 90,
       95])

**2D array

In [ ]:
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2)
print(arr2.size)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
9


**2D array indexing(similar to what is done in C and C++)

In [ ]:
arr2[2][1]

8

**Finding a subpart of a matrix:
To get the subpart of a matrix: " : value " will consider all rows/columns before that value row/column(exclusive). " value : " will consider all rows/columns after value row/column(inclusive).

In [ ]:
arr2[:1,1:]

array([[2, 3]])

**Boolean array

In [ ]:
print(arr1)

[10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [ ]:
boolean_array = ((arr1 % 3)==0)
print(boolean_array)

[False  True False False  True False False  True False False  True False
 False  True False False  True False]


**Arithmetic operations on arrays

In [ ]:
print(arr1 + arr1)

[ 20  30  40  50  60  70  80  90 100 110 120 130 140 150 160 170 180 190]


In [ ]:
a = np.arange(0,35,2)
print(a)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34]


In [ ]:
print(arr1 * a) #element wise multiplication

[   0   30   80  150  240  350  480  630  800  990 1200 1430 1680 1950
 2240 2550 2880 3230]


In [ ]:
a1 = np.array([[10,20,30],[40,50,60]])
print(a1.shape)
a2 = np.array([[1,2],[3,4],[5,6]])
print(a2.shape)

(2, 3)
(3, 2)


In [ ]:
print(a1)
print(a2.T)

[[10 20 30]
 [40 50 60]]
[[1 3 5]
 [2 4 6]]


In [ ]:
print(a1*a2) #element wise multiplication is not possible unless the shapes are same

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [ ]:
print(a1*(a2.T))

[[ 10  60 150]
 [ 80 200 360]]


**Understanding the difference between normal matrix multiplication(dot product) and element-wise-multiplication

(2 * 3) * (3 * 2) --> (2 * 2)

In [ ]:
print(np.dot(a1,a2))

[[220 280]
 [490 640]]


(3 * 2) * ( 2 * 3) --> (3 * 3)

In [ ]:
print(np.dot(a2,a1))

[[ 90 120 150]
 [190 260 330]
 [290 400 510]]


In [ ]:
print(np.multiply(a1,a1))
print(np.multiply(a2,a2))
print(np.multiply(a1.T,a1.T))
print(np.multiply(a2.T,a2.T))

[[ 100  400  900]
 [1600 2500 3600]]
[[ 1  4]
 [ 9 16]
 [25 36]]
[[ 100 1600]
 [ 400 2500]
 [ 900 3600]]
[[ 1  9 25]
 [ 4 16 36]]


**flattening an array of multiple dimensions into a single dimension

In [ ]:
a1.ravel()

array([10, 20, 30, 40, 50, 60])

In [ ]:
a2.ravel()

array([1, 2, 3, 4, 5, 6])